[build]
  publish = "/"
  command = "npm ci"

[dev]
  command = "npm start"
  port = 8000
  targetPort = 3000

[template.environment]
  NETLIFY_CMS_OAUTH_PROVIDER = "github"
  NETLIFY_CMS_OAUTH_CLIENT_ID = "Ov23liEilXsyPhBjM8IH"
  NETLIFY_CMS_OAUTH_CLIENT_SECRET = "ff4a8e07d21c35bf065e14732754b11568d06e9c"

[[headers]]
  for = "/admin/*"
    [headers.values]
    Basic-Auth = "admin:backfills"